### ISSUE TITLE
showing subnet... 

### ISSUE THREAD

**Issue by gilcot** [rendicott/pySser#4] opened 2017-04-19 19:54 UTC
As mentionned in #3 when I try for example `python pysser -c config.ini --filtersubnet=172.10.36.0` nothing comes out. With  `python pysser -c config.ini --filtersubnet=172.10.36.0 -d DEBUG` I can see in `pysser.py.log` file that the subnet is retrieved but not displayed. 
(I'm opening this issue as it's not related to the accented values)

**Comment by rendicott** [comment] 2017-04-19 19:58
Can you send me your config.ini? (and scrub passwords obviously)

**Comment by gilcot** [comment] 2017-04-19 20:20
Well, well, for subnet not being displayed it looks like a design choice... 
In fact, some functions (def) in `pysser.py` do have a `print(message)` at end: `dump_ansible`, `claim_address`, `modify_address`, `release_address`, `search_for_hostname`. Others don't; they only return their result for further process 'cause they are called by some other function. And here the documentation is not clear about this filter, because the code is designed so that it works with `--firstavailable` or `claimip` and maybe some other I didn't manage to found. 

After some hours (that's because I don't know much _Python_) I found a way to solve it. 
First, add a call to handle that special case (it works but need more test to be sure it doesn't interfer with other options, maybe in the `if` statement exclude options that may be combined with it?) 
![sub1](https://cloud.githubusercontent.com/assets/27341580/25200181/b31d8b98-254d-11e7-966e-b7a065bdaf1a.PNG)
 Second, a funtion whose purpose is to print the result out (the formating should be changed to TSV but it's another step) 
![sub2](https://cloud.githubusercontent.com/assets/27341580/25200275/027f2728-254e-11e7-8f03-c5da54d06c00.PNG)
First tests look promising 
![sub3](https://cloud.githubusercontent.com/assets/27341580/25200383/6489b4c4-254e-11e7-916a-f7c692d5035f.PNG)

**Comment by gilcot** [comment] 2017-04-19 20:28
Hello REndicott

I missed your reply because doing some last test and taking screenshots for the solution found. 
Here is the `config.ini` (renamed to `config.txt` as the original file type is not supported by _github_ ) 
[config.txt](https://github.com/rendicott/pySser/files/938176/config.txt)
 
Thanks.

**Comment by rendicott** [comment] 2017-04-19 21:37
I guess I'm confused as to what problem you're trying to solve. Basically
the script won't display anything to stdout by design unless you pass the
--list option.

**Comment by gilcot** [comment] 2017-04-20 13:50
Thank you for the quick reply. 

If it's a design choice then this issue can be closed. But the readme should be updated in a way or another. For what I understood, each option may work alone (and in conjunction with some others when mentionned, like for `--firstavailable`) So, naively, I expected the example given, i.e `python pysser.py --configfile myconfig.ini --filtersubnet 10.119.6.0`, to work like `python pysser.py --configfile myconfig.ini --searchhostname a-short-name` 
For my use then, I end up with
![sub4](https://cloud.githubusercontent.com/assets/27341580/25233921/c57134dc-25e0-11e7-95a4-ab2d35a6e208.PNG)
and 
![sub5](https://cloud.githubusercontent.com/assets/27341580/25233968/eac241e0-25e0-11e7-9d21-c5d7e54ac2af.PNG)

I'll play with `--list` today.

Regards.

**Comment by rendicott** [comment] 2018-05-03 03:00
Closing since I think this was resolved.

**Closed as completed by rendicott** 2018-05-03 03:00 UTC
